// ***** start - import from package
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// ***** end - import from package

// ***** start - import from files
import "./globals.css";
// ***** end - import from files

// **** start - define fonts *****
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
// **** end - define fonts *****

// **** start - Add page title and description *****
export const metadata: Metadata = {
  title: "Devx Assignement Kenil",
  description: "Generated by kenil product listing page",
};
// **** end - Add page title and description *****

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          {children}
      </body>
    </html>
  );
}
